"""Build the supplementary 52-pair allocator matrix table."""

from __future__ import annotations

import argparse
import hashlib
import json
import os
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[2]
DEFAULT_SOURCE = ROOT / "results/verified/2026-08-14/capacity-phase-formal-corrected.analysis.json"
DEFAULT_OUTPUT = ROOT / "paper/mlsys2026/capacity_matrix_table.tex"


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def load_analysis(path: Path) -> tuple[dict[str, Any], str]:
    sidecar = path.with_suffix(path.suffix + ".sha256")
    if not path.is_file() or not sidecar.is_file():
        raise SystemExit(f"missing capacity analysis or SHA-256 sidecar: {path}")
    digest = sha256_file(path)
    if sidecar.read_text(encoding="ascii").strip() != digest:
        raise SystemExit(f"SHA-256 verification failed: {path}")

    data = json.loads(path.read_text(encoding="utf-8"))
    if data.get("schema_version") != 1 or data.get("phase") != "formal":
        raise SystemExit("expected schema-1 formal capacity analysis")
    if data.get("n_cells") != 112:
        raise SystemExit(f"expected 112 capacity cells, found {data.get('n_cells')!r}")
    rows = data.get("rows")
    if not isinstance(rows, list) or len(rows) != 52:
        raise SystemExit(f"expected 52 paired rows, found {len(rows) if isinstance(rows, list) else None}")
    summary = data.get("prediction_residual_summary", {})
    if summary.get("n_pairs") != 52:
        raise SystemExit("residual summary does not cover all 52 pairs")

    keys: set[tuple[str, str, int, float]] = set()
    for row in rows:
        key = (
            str(row["model"]),
            str(row["kv_dtype"]),
            int(row["length"]),
            float(row["gpu_memory_utilization"]),
        )
        if key in keys:
            raise SystemExit(f"duplicate capacity pair: {key}")
        keys.add(key)
        if int(row["bf16_state_tokens"]) <= int(row["fp32_state_tokens"]):
            raise SystemExit(f"nonpositive bf16-state capacity gain: {key}")
    return data, digest


def format_row(row: dict[str, Any]) -> str:
    fp32_tokens = int(row["fp32_state_tokens"])
    bf16_tokens = int(row["bf16_state_tokens"])
    gain_pct = 100.0 * (bf16_tokens / fp32_tokens - 1.0)
    residual_pct = float(row["prediction_residual_pct"])
    return (
        f"{str(row['model']).upper()} & {row['kv_dtype']} & {int(row['length']):,} & "
        f"{float(row['gpu_memory_utilization']):.2f} & "
        f"{int(row['fp32_num_gpu_blocks']):,} & {int(row['bf16_num_gpu_blocks']):,} & "
        f"{fp32_tokens:,} & {bf16_tokens:,} & {gain_pct:.2f}\\% & "
        f"{residual_pct:+.2f}\\% \\\\"
    )


def render_table(data: dict[str, Any], source: Path, digest: str) -> str:
    try:
        source_label = source.resolve().relative_to(ROOT).as_posix()
    except ValueError:
        source_label = source.resolve().as_posix()
    lines = [
        "% Generated by scripts/bench/build_capacity_matrix_table.py.",
        f"% Source: {source_label}",
        f"% Source SHA-256: {digest}",
        r"\begingroup",
        r"\scriptsize",
        r"\setlength{\tabcolsep}{3.0pt}",
        r"\renewcommand{\arraystretch}{0.94}",
        r"\setcounter{LTchunksize}{100}",
        r"\begin{longtable}{@{}llrrrrrrrr@{}}",
        r"\caption{\textbf{Complete formal allocator matrix.} $K$ is the allocated GPU-block count and $T$ is total allocator token capacity. Gain is $100(T_{16}/T_{32}-1)$; residual is the signed measured-to-continuous state-ratio error. The 52 rows come from attempt \texttt{capacity-phase-formal-20260811}; they are allocator measurements, not scheduler-admitted concurrency.}",
        r"\label{tab:full-capacity}\\",
        r"\toprule",
        r"Model & KV & $L$ & $u$ & $K_{32}$ & $K_{16}$ & $T_{32}$ & $T_{16}$ & Gain & Resid.\\",
        r"\midrule",
        r"\endfirsthead",
        r"\multicolumn{10}{l}{\tablename\ \thetable\ (continued)}\\",
        r"\toprule",
        r"Model & KV & $L$ & $u$ & $K_{32}$ & $K_{16}$ & $T_{32}$ & $T_{16}$ & Gain & Resid.\\",
        r"\midrule",
        r"\endhead",
        r"\midrule",
        r"\multicolumn{10}{r}{Continued on next page}\\",
        r"\endfoot",
        r"\bottomrule",
        r"\endlastfoot",
    ]
    lines.extend(format_row(row) for row in data["rows"])
    lines.extend([r"\end{longtable}", r"\endgroup", ""])
    return "\n".join(lines)


def atomic_write(path: Path, payload: str) -> str:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_name(f".{path.name}.tmp-{os.getpid()}")
    with tmp.open("w", encoding="utf-8", newline="\n") as handle:
        handle.write(payload)
        handle.flush()
        os.fsync(handle.fileno())
    os.replace(tmp, path)
    digest = sha256_file(path)
    path.with_suffix(path.suffix + ".sha256").write_text(f"{digest}\n", encoding="ascii")
    return digest


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source", type=Path, default=DEFAULT_SOURCE)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    data, source_digest = load_analysis(args.source)
    payload = render_table(data, args.source, source_digest)
    if args.check:
        if not args.output.is_file() or args.output.read_text(encoding="utf-8") != payload:
            raise SystemExit(f"capacity matrix table is missing or stale: {args.output}")
        output_digest = sha256_file(args.output)
        sidecar = args.output.with_suffix(args.output.suffix + ".sha256")
        if not sidecar.is_file() or sidecar.read_text(encoding="ascii").strip() != output_digest:
            raise SystemExit(f"capacity matrix table sidecar is missing or stale: {sidecar}")
    else:
        output_digest = atomic_write(args.output, payload)
    print(
        json.dumps(
            {
                "status": "PASS",
                "mode": "check" if args.check else "write",
                "rows": len(data["rows"]),
                "source_sha256": source_digest,
                "output_sha256": output_digest,
            },
            indent=2,
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
